<?php

namespace Meritt\CandySort\Business;

use \TestData\CreateCandidateData;
use \TestData\CreateExamData;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2013-09-29 at 23:22:31.
 */
class ExamSorterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Meritt\CandySort\Domain\Exam
     */
    protected $exam;

    /**
     * @var \Meritt\CandySort\Domain\CandidateAnswers
     */
    protected $allCandidateAnswers;

    /**
     * @var \Meritt\CandySort\Business\ExamSorter
     */
    protected $sorter;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->exam = CreateExamData::create();
        $this->allCandidateAnswers = CreateCandidateData::create();
        $this->sorter = new ExamSorter($this->exam);
    }

    /**
     * @covers Meritt\CandySort\Business\ExamSorter::sort
     */
    public function testSort()
    {
        $sorted = $this->sorter->sort($this->allCandidateAnswers);
        $this->assertEquals(array(
            $this->allCandidateAnswers[0],
            $this->allCandidateAnswers[4],
            $this->allCandidateAnswers[3],
            $this->allCandidateAnswers[1],
            $this->allCandidateAnswers[2]
        ), $sorted);
    }

}
